# Generated by Django 3.1.2 on 2020-10-24 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_name', models.CharField(blank=True, max_length=150, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('batch_no', models.IntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('reorder_level', models.IntegerField(blank=True, default=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('Available', 'Item is currently available'), ('Restocking', 'Currently out of stock')], default='Available', max_length=20, null=True)),
                ('last_updated', models.DateField(null=True)),
                ('timestamp', models.DateField(null=True)),
                ('mode_of_sales', models.CharField(blank=True, choices=[('General', 'General'), ('Give away', 'Give away')], default='General', max_length=50, null=True)),
                ('quantity_sold', models.IntegerField(blank=True, default=0, null=True)),
                ('amount', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity_restocked', models.IntegerField(blank=True, default=0, null=True)),
                ('download_csv', models.BooleanField(default=False)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('store', models.IntegerField(blank=True, default=0, null=True)),
                ('variance', models.IntegerField(blank=True, default=0, null=True)),
                ('available', models.IntegerField(blank=True, default=0, null=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
            ],
        ),
    ]
